# config/packages/security.yaml
security:
    encoders:
        App\Entity\Users:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                target: default
    access_control:
        - { path: ^/settings, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
